addSbtPlugin(dependency = "com.47deg"         % "sbt-microsites" % "1.1.2")
addSbtPlugin(dependency = "com.github.gseitz" % "sbt-release"    % "1.0.11")
addSbtPlugin(dependency = "com.jsuereth"      % "sbt-pgp"        % "2.0.0")
addSbtPlugin(dependency = "com.timushev.sbt"  % "sbt-updates"    % "0.4.2")
addSbtPlugin(dependency = "org.scalameta"     % "sbt-mdoc"       % "2.1.1")
addSbtPlugin(dependency = "org.scalameta"     % "sbt-scalafmt"   % "2.0.4")
